stages:
  - docker

build_and_push_image:
  stage: docker
  variables:
    IMAGE_VERSION: "1.0"
  script:
    - docker login -u majumi -p uaimrzadzi
    - docker build -t majumi/bsoskaner:$IMAGE_VERSION
    - docker push majumi/bsoskaner:$IMAGE_VERSION
    - docker logout
  tags:
    - docker